name: Build Atlantis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Atlantis
        uses: docker/build-push-action@v4
        with:
          context: containers/atlantis
          platforms: linux/arm64, linux/amd64, linux/arm/v7
          push: true
          tags: ghcr.io/peakematt/atlantis:latest
