name: Build Atlantis

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Atlantis
        uses: docker/build-push-action@v4
        with:
          context: atlantis
          platforms: linux/arm64, linux/amd64, linux/arm/v7
          push: true
          sbom: true
          tags: ghcr.io/peakematt/atlantis:latest
